routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::middleware(['check.role:admin'])->group(function () {
        Route::prefix('admin')->group(function () {
            Route::get('/', 'AdminController@index')->name('admin.home');
            Route::resource('users', 'AdminUserController');
            Route::resource('products', 'AdminProductController');
            Route::get('/export/product/{product}', 'AdminProductController@export')->name('admin.export');
            Route::get('/products-data', 'AdminProductController@productsData')->name('admin.products_data');
            /*Route::get('/test', function () {
                return view('welcome');
            });*/
        });
    });
    Route::middleware(['check.status', 'check.role:customer'])->group(function () {
        Route::prefix('product')->group(function () {
            Route::get('/', 'ProductController@index')->name('product.home');
            Route::post('/filtered', 'ProductController@filtered')->name('product.filtered');
            Route::get('/filtered', 'ProductController@index');
            Route::post('/search', 'ProductController@search');
        });

        Route::prefix('cart')->group(function () {
            Route::post('/store', 'CartController@store')->name('cart.store');
            Route::get('/', 'CartController@index')->name('cart.show');
            Route::post('/update', 'CartController@update')->name('cart.update');
            Route::get('/reset', 'CartController@reset')->name('cart.reset');
        });

        Route::prefix('order')->group(function () {
            Route::post('/store', 'OrderController@store')->name('order.store');
            Route::get('/create', 'OrderController@create')->name('order.create');
            Route::get('/thankyou/{order}', 'OrderController@thankyou')->name('order.thankyou');
        });
    });
});

app/Http/Controllers/AdminProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Services\ProductService;
use App\Services\CategoryService;
use App\Models\Product;
use App\Http\Requests\ProductStore;
use App\Http\Requests\ProductEdit;
use PDF;
use DataTables;
use Illuminate\Support\Facades\View;

class AdminProductController extends Controller
{
    public function __construct(ProductService $product, CategoryService $category)
    {
        $this->product = $product;
        $this->category = $category;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin_product.index', ["products" => $this->product->all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin_product.create', ['categories' => $this->category->all()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ProductStore $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductStore $request)
    {
        $path = $request->file('image')->store(config('variables.default_product_image_path'));
        $imageName = str_replace(config('variables.default_product_image_path') . DIRECTORY_SEPARATOR, "", $path);
        $this->product->create($request->except('image') + ["image" => $imageName]);
        return redirect()->route("products.index");
    }

    /**
     * Display the specified resource.
     *
     * @param Product $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('admin_product.show', ["product" => $product]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Product $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view('admin_product.edit', ["product" => $product, 'categories' => $this->category->all()]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param ProductEdit $request
     * @param Product $product
     * @return \Illuminate\Http\Response
     */
    public function update(ProductEdit $request, Product $product)
    {
        $data = $request->all();
        unset($data['image']);
        if (!empty($request->file('image'))) {
            if (!empty($product->image)) {
                $path = $request->file('image')->storeAs(
                    config('variables.default_product_image_path'),
                    $product->image
                );
            } else {
                $path = $request->file('image')->store(config('variables.default_product_image_path'));
                $data['image'] = str_replace(config('variables.default_product_image_path') . DIRECTORY_SEPARATOR, "", $path);
            }
        }
        $this->product->update($product->id, $data);
        return redirect()->route('products.show', ['product' => $product->id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param Product $product
     * @return \Illuminate\Http\Response
     */
    public function export(Product $product)
    {
        $pdf = PDF::loadView('pdf.product', ["product" => $product]);
        $pdf->save('product.pdf');
    }

    public function productsData()
    {
        $products = $this->product->all()->toArray();
        foreach($products as &$product){
            $product['category_name'] = $product['category']['name'];
            $product['action'] = View::make('admin_product.action_block', ['product' => $product])->render();
        } unset($product);
        return DataTables::of($products)->make(true);
    }
}

resources/views/admin_product/action_block.blade.php
<div class="btn-group">
    <button type="button" class="btn btn-info">Action</button>
    <button type="button" class="btn btn-info dropdown-toggle dropdown-icon" data-toggle="dropdown" aria-expanded="false">
        <span class="sr-only">Toggle Dropdown</span>
        <div class="dropdown-menu" role="menu" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(-1px, 37px, 0px);">
            <a class="dropdown-item" onclick="location.href = '/admin/products/{{ $product['id'] }}';" href="/admin/products/{{ $product['id'] }}">Show</a>
            <a class="dropdown-item" onclick="location.href = '/admin/products/{{ $product['id'] }}/edit';" href="/admin/products/{{ $product['id'] }}/edit">Edit</a>
            <a class="dropdown-item" onclick="location.href = '/admin/export/product/{{ $product['id'] }}';" href="/admin/export/product/{{ $product['id'] }}">Export PDF</a>
        </div>
    </button>
</div>

resources/views/admin_product/create.blade.php
@extends('adminlte::page')

@section('title', 'Product Creation')

@section('content')
    <div class="card-body">
        <form method="POST" action="{{route("products.store")}}" enctype="multipart/form-data">
            @csrf
            <div class="row">
                <div class="col-md-6">
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Product Creation</h3>

                            <div class="card-tools">
                                <button type="button" class="btn btn-tool" data-card-widget="collapse"
                                        data-toggle="tooltip" title="Collapse">
                                    <i class="fas fa-minus"></i></button>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <label for="inputName">Name</label>
                                <input type="text" name="name" value="{{ old('name') }}" id="name" class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}">
                                @if($errors->has('name'))
                                    <div class="invalid-feedback">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </div>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="inputDescription">Price</label>
                                <input type="text" name="price" value="{{ old('price') }}" id="price" class="form-control {{ $errors->has('price') ? 'is-invalid' : '' }}">
                                @if($errors->has('price'))
                                    <div class="invalid-feedback">
                                        <strong>{{ $errors->first('price') }}</strong>
                                    </div>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="inputStatus">Quantity</label>
                                <input type="text" name="quantity" value="{{ old('quantity') }}" id="quantity" class="form-control {{ $errors->has('quantity') ? 'is-invalid' : '' }}">
                                @if($errors->has('quantity'))
                                    <div class="invalid-feedback">
                                        <strong>{{ $errors->first('quantity') }}</strong>
                                    </div>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="inputStatus">Category</label>
                                <select name="category_id" class="form-control custom-select {{ $errors->has('category_id') ? 'is-invalid' : '' }}">
                                    <option selected="" disabled="">Select category</option>
                                    @foreach($categories as $category)
                                        <option {{ old('category_id') == $category->id ? "selected" : "" }} value="{{$category->id}}">{{$category->name}}</option>
                                    @endforeach
                                </select>
                                @if($errors->has('category_id'))
                                    <div class="invalid-feedback">
                                        <strong>{{ $errors->first('category_id') }}</strong>
                                    </div>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="exampleInputFile">File input</label>
                                <div class="input-group">
                                    <div class="custom-file">
                                        <input type="file" name="image" class="custom-file-input {{ $errors->has('image') ? 'is-invalid' : '' }}" id="exampleInputFile">
                                        <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                                    </div>
                                    <div class="input-group-append">
                                        <span class="input-group-text" id="">Upload</span>
                                    </div>
                                </div>
                                @if($errors->has('image'))
                                    <div class="invalid-feedback">
                                        <strong>{{ $errors->first('image') }}</strong>
                                    </div>
                                @endif
                            </div>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div>
            <div class="row">
                <div class="col-6">
                    <a href="/admin" class="btn btn-secondary">Cancel</a>
                    <input type="submit" value="Create Product" class="btn btn-success float-right">
                </div>
            </div>
        </form>
    </div>
@stop

@section('js')
    <script>
    </script>
@stop

resources/views/admin_product/edit.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content')
    <div class="card-body">
        <form method="POST" action="{{route("products.update", ['product' => $product->id])}}" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="row">
                <div class="col-md-6">
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Product Edit</h3>

                            <div class="card-tools">
                                <button type="button" class="btn btn-tool" data-card-widget="collapse"
                                        data-toggle="tooltip" title="Collapse">
                                    <i class="fas fa-minus"></i></button>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <label for="inputName">Name</label>
                                <input type="text" name="name" value="{{ old('name') ?? $product->name }}" id="name"
                                       class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}">
                                @if($errors->has('name'))
                                    <div class="invalid-feedback">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </div>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="inputDescription">Price</label>
                                <input type="text" name="price" value="{{ old('price') ?? $product->price }}" id="price"
                                       class="form-control {{ $errors->has('price') ? 'is-invalid' : '' }}">
                                @if($errors->has('price'))
                                    <div class="invalid-feedback">
                                        <strong>{{ $errors->first('price') }}</strong>
                                    </div>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="inputStatus">Quantity</label>
                                <input type="text" name="quantity" value="{{ old('quantity') ?? $product->quantity }}" id="quantity"
                                       class="form-control {{ $errors->has('quantity') ? 'is-invalid' : '' }}">
                                @if($errors->has('quantity'))
                                    <div class="invalid-feedback">
                                        <strong>{{ $errors->first('quantity') }}</strong>
                                    </div>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="inputStatus">Category</label>
                                <select name="category_id"
                                        class="form-control custom-select {{ $errors->has('category_id') ? 'is-invalid' : '' }}">
                                    <option selected="" disabled="">Select category</option>
                                    @foreach($categories as $category)
                                        <option
                                            {{ (old('category_id') == $category->id || (empty(old('category_id')) && $product->category_id == $category->id)) ? "selected" : "" }} value="{{$category->id}}">{{$category->name}}</option>
                                    @endforeach
                                </select>
                                @if($errors->has('category_id'))
                                    <div class="invalid-feedback">
                                        <strong>{{ $errors->first('category_id') }}</strong>
                                    </div>
                                @endif
                            </div>
                            <div class="form-group">
                                @if (!empty($product->image))
                                    <img class="img-fluid product-img" src="/storage/products/{{ $product->image }}">
                                @endif
                                <label for="exampleInputFile">File input</label>
                                <div class="input-group">
                                    <div class="custom-file">
                                        <input type="file" name="image"
                                               class="custom-file-input {{ $errors->has('image') ? 'is-invalid' : '' }}"
                                               id="exampleInputFile">
                                        <label class="custom-file-label" for="exampleInputFile">Choose new file</label>
                                    </div>
                                    <div class="input-group-append">
                                        <span class="input-group-text" id="">Change</span>
                                    </div>
                                </div>
                                @if($errors->has('image'))
                                    <div class="invalid-feedback">
                                        <strong>{{ $errors->first('image') }}</strong>
                                    </div>
                                @endif
                            </div>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div>
            <div class="row">
                <div class="col-6">
                    <a href="/admin" class="btn btn-secondary">Cancel</a>
                    <input type="submit" value="Edit Product" class="btn btn-success float-right">
                </div>
            </div>
        </form>
    </div>
@stop

@section('js')
    <script>
    </script>
@stop

resources/views/admin_product/index.blade.php
@extends('adminlte::page')

@section('title', 'Products')

@section('content')
    <div class="card-body">
        <div id="example1_wrapper">
            <div class="row">
                <div class="col-sm-12">
                    <table id="example1" class="table table-bordered table-striped" role="grid"
                           aria-describedby="example1_info">
                        <thead>
                        <tr role="row">
                            <th>
                                #
                            </th>
                            <th>
                                Name
                            </th>
                            <th>
                                Price
                            </th>
                            <th>
                                Category Id
                            </th>
                            <th>
                                Actions
                            </th>
                            <th>

                            </th>
                        </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
@stop

@section('js')
    <script>
        $(function () {
            $('#example1').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
                "processing": true,
                "serverSide": true,
                "ajax": '{!! route('admin.products_data') !!}',
                "columns": [
                    { data: 'id', name: 'id' },
                    { data: 'name', name: 'name' },
                    { data: 'price', name: 'price' },
                    { data: 'category_name', name: 'category' },
                    { data: 'action', name: 'action' }
                ]
            });
        });
    </script>
@stop

resources/views/admin_product/show.blade.php
@extends('adminlte::page')

@section('title', 'Show Product')

@section('content')
    <div class="card-body">
        <div class="row">
            <div class="col-12 col-sm-6 col-md-6 align-items-stretch">
                <div class="card bg-light">
                    <div class="card-header text-muted border-bottom-0">
                    </div>
                    <div class="card-body pt-0">
                        <div class="row">
                            <div class="col-9">
                                <h2 class="lead"><b>#{{ $product->id }} {{ $product->name }}</b></h2>
                                <p class="text-muted text-sm">$@money($product->price)</p>
                                <p class="text-muted text-sm"><b>Quantity:</b> {{ $product->quantity }}</p>
                                <p class="text-muted text-sm"><b>Category:</b> #{{ $product->category_id }} {{ $product->category->name }}</p>
                                <p class="text-muted text-sm">
                                    @if (!empty($product->image))
                                        <img class="img-fluid product-img" src="/storage/products/{{ $product->image }}">
                                    @else
                                        <img class="img-fluid product-img"
                                             src="/storage/products/{{ config('variables.default_product_image') }}">
                                    @endif
                                </p>
                                <p class="text-muted text-sm"><b>Create Time:</b> {{ $product->created_at }}</p>
                            </div>
                            <div class="col-5 text-center">
                                <img src="../../dist/img/user1-128x128.jpg" alt="" class="img-circle img-fluid">
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="text-right">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@section('js')
    <script>

    </script>
@stop