routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::middleware(['check.role:admin'])->group(function () {
        Route::prefix('admin')->group(function () {
            Route::get('/', 'AdminController@index')->name('admin.home');
            Route::resource('users', 'AdminUserController');
            Route::resource('products', 'AdminProductController');
            Route::get('/export/product/{product}', 'AdminProductController@export')->name('admin.export');
            Route::get('/products-data', 'AdminProductController@productsData')->name('admin.products_data');
            /*Route::get('/test', function () {
                return view('welcome');
            });*/
        });
    });
    Route::middleware(['check.status', 'check.role:customer'])->group(function () {
        Route::prefix('product')->group(function () {
            Route::get('/', 'ProductController@index')->name('product.home');
            Route::post('/filtered', 'ProductController@filtered')->name('product.filtered');
            Route::get('/filtered', 'ProductController@index');
            Route::post('/search', 'ProductController@search');
        });

        Route::prefix('cart')->group(function () {
            Route::post('/store', 'CartController@store')->name('cart.store');
            Route::get('/', 'CartController@index')->name('cart.show');
            Route::post('/update', 'CartController@update')->name('cart.update');
            Route::get('/reset', 'CartController@reset')->name('cart.reset');
        });

        Route::prefix('order')->group(function () {
            Route::post('/store', 'OrderController@store')->name('order.store');
            Route::get('/create', 'OrderController@create')->name('order.create');
            Route::get('/thankyou/{order}', 'OrderController@thankyou')->name('order.thankyou');
        });
    });
});

app/Http/Controllers/AdminUserController.php
<?php

namespace App\Http\Controllers;

use App\Services\CartService;
use Illuminate\Http\Request;
use App\Services\UserService;
use App\Http\Requests\UserStore;
use App\Models\User;
use App\Http\Requests\UserEdit;

class AdminUserController extends Controller
{
    public function __construct(UserService $user)
    {
        $this->user = $user;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin_user.index', ["users" => $this->user->all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin_user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param UserStore $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserStore $request)
    {
        $this->user->create($request->all());
        return redirect()->route("users.index");
    }

    /**
     * Display the specified resource.
     *
     * @param  User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('admin_user.show', ["user" => $user]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('admin_user.edit', ["user" => $user]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  UserEdit
     * @param  User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(UserEdit $request, User $user)
    {
        $this->user->update($user->id, $request->all());
        return redirect()->route('users.show', ['user' => $user->id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin_user/create.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content')
    <div class="card-body">
        <form method="POST" action="{{route("users.store")}}">
            @csrf
            <div class="row">
                <div class="col-md-6">
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">User Creation</h3>

                            <div class="card-tools">
                                <button type="button" class="btn btn-tool" data-card-widget="collapse"
                                        data-toggle="tooltip" title="Collapse">
                                    <i class="fas fa-minus"></i></button>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <label for="inputName">Name</label>
                                <input type="text" name="name" value="{{ old('name') }}" id="name" class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}">
                                @if($errors->has('name'))
                                    <div class="invalid-feedback">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </div>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="inputDescription">Email</label>
                                <input type="email" name="email" value="{{ old('email') }}" id="email" class="form-control {{ $errors->has('email') ? 'is-invalid' : '' }}">
                                @if($errors->has('email'))
                                    <div class="invalid-feedback">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </div>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="inputStatus">Status</label>
                                <select name="status" class="form-control custom-select {{ $errors->has('status') ? 'is-invalid' : '' }}">
                                    <option selected="" disabled="">Select one</option>
                                    <option {{ old('status') == 'Active' ? "selected" : "" }} value="Active">Active</option>
                                    <option {{ old('status') == 'Locked' ? "selected" : "" }} value="Locked">Locked</option>
                                    <option {{ old('status') == 'Inactive' ? "selected" : "" }} value="Inactive">Inactive</option>
                                </select>
                                @if($errors->has('status'))
                                    <div class="invalid-feedback">
                                        <strong>{{ $errors->first('status') }}</strong>
                                    </div>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="inputPassword">Password</label>
                                <input type="password" name="password" id="inputPassword" class="form-control {{ $errors->has('password') ? 'is-invalid' : '' }}">
                                @if($errors->has('password'))
                                    <div class="invalid-feedback">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </div>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="inputPasswordConf">Confirm Password</label>
                                <input type="password" name="password_confirmation" id="inputPasswordConf"
                                       class="form-control">
                            </div>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div>
            <div class="row">
                <div class="col-6">
                    <a href="/admin" class="btn btn-secondary">Cancel</a>
                    <input type="submit" value="Create new User" class="btn btn-success float-right">
                </div>
            </div>
        </form>
    </div>
@stop

@section('js')
    <script>
    </script>
@stop

resources/views/admin_user/edit.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content')
    <div class="card-body">
        <form method="POST" action="{{route("users.update", ['user' => $user->id])}}">
            @csrf
            @method('PUT')
            <div class="row">
                <div class="col-md-6">
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">User Edit</h3>

                            <div class="card-tools">
                                <button type="button" class="btn btn-tool" data-card-widget="collapse"
                                        data-toggle="tooltip" title="Collapse">
                                    <i class="fas fa-minus"></i></button>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <label for="inputName">Name</label>
                                <input type="text" name="name" value="{{ old('name') ?? $user->name }}" id="name" class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}">
                                @if($errors->has('name'))
                                    <div class="invalid-feedback">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </div>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="inputDescription">Email</label>
                                <input type="email" name="email" value="{{ old('email') ?? $user->email }}" id="email" class="form-control {{ $errors->has('email') ? 'is-invalid' : '' }}">
                                @if($errors->has('email'))
                                    <div class="invalid-feedback">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </div>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="inputStatus">Status</label>
                                <select name="status" class="form-control custom-select {{ $errors->has('status') ? 'is-invalid' : '' }}">
                                    <option selected="" disabled="">Select one</option>
                                    <option {{ (old('status') == 'Active' || (empty(old('status')) && $user->status == 'Active')) ? "selected" : "" }} value="Active">Active</option>
                                    <option {{ (old('status') == 'Locked' || (empty(old('status')) && $user->status == 'Locked')) ? "selected" : "" }} value="Locked">Locked</option>
                                    <option {{ (old('status') == 'Inactive' || (empty(old('status')) && $user->status == 'Inactive')) ? "selected" : "" }} value="Inactive">Inactive</option>
                                </select>
                                @if($errors->has('status'))
                                    <div class="invalid-feedback">
                                        <strong>{{ $errors->first('status') }}</strong>
                                    </div>
                                @endif
                            </div>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div>
            <div class="row">
                <div class="col-6">
                    <a href="/admin" class="btn btn-secondary">Cancel</a>
                    <input type="submit" value="Edit User" class="btn btn-success float-right">
                </div>
            </div>
        </form>
    </div>
@stop

@section('js')
    <script>
    </script>
@stop

resources/views/admin_user/index.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content')
    <div class="card-body">
        <div id="example1_wrapper">
            <div class="row">
                <div class="col-sm-12">
                    <table id="example1" class="table table-bordered table-striped" role="grid"
                           aria-describedby="example1_info">
                        <thead>
                        <tr role="row">
                            <th>
                                #
                            </th>
                            <th>
                                Name
                            </th>
                            <th>
                                Email
                            </th>
                            <th>
                                Status
                            </th>
                            <th>
                                Actions
                            </th>
                            <th>

                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($users as $user)
                        <tr>
                            <td>{{ $user->id }}</td>
                            <td>{{ $user->name }}</td>
                            <td>{{ $user->email }}</td>
                            <td>{{ $user->status }}</td>
                            <td>
                                <div class="btn-group">
                                    <button type="button" class="btn btn-info">Action</button>
                                    <button type="button" class="btn btn-info dropdown-toggle dropdown-icon" data-toggle="dropdown" aria-expanded="false">
                                        <span class="sr-only">Toggle Dropdown</span>
                                        <div class="dropdown-menu" role="menu" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(-1px, 37px, 0px);">
                                            <a class="dropdown-item" onclick="location.href = '/admin/users/{{ $user->id }}';" href="/admin/users/{{ $user->id }}">Show</a>
                                            <a class="dropdown-item" onclick="location.href = '/admin/users/{{ $user->id }}/edit';" href="/admin/users/{{ $user->id }}/edit">Edit</a>
                                            <!--<a class="dropdown-item" href="#">Delete</a>-->
                                        </div>
                                    </button>
                                </div>
                            </td>
                            <td>
                                <form>
                                    <input type="submit" class="btn btn-danger" value="DELETE">
                                </form>
                            </td>
                        </tr>
                        @endforeach
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
@stop

@section('js')
    <script>
        $(function () {
            $('#example1').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>
@stop

resources/views/admin_user/show.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content')
    <div class="card-body">
        <div class="row">
            <div class="col-12 col-sm-6 col-md-6 align-items-stretch">
                <div class="card bg-light">
                    <div class="card-header text-muted border-bottom-0">
                    </div>
                    <div class="card-body pt-0">
                        <div class="row">
                            <div class="col-9">
                                <h2 class="lead"><b>{{ $user->name }}</b></h2>
                                <p class="text-muted text-sm">{{ $user->email }}</p>
                                <p class="text-muted text-sm"><b>Type:</b> {{ $user->type }}</p>
                                <p class="text-muted text-sm"><b>Status:</b> {{ $user->status }}</p>
                                <p class="text-muted text-sm"><b>Incorrect Logins:</b> {{ $user->incorrect_login_attempts }}</p>
                                <p class="text-muted text-sm"><b>Create Time:</b> {{ $user->created_at }}</p>
                            </div>
                            <div class="col-5 text-center">
                                <img src="../../dist/img/user1-128x128.jpg" alt="" class="img-circle img-fluid">
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="text-right">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@section('js')
    <script>

    </script>
@stop